---
title: "11-GHA Pointblank Demo"
author: Ramanathan Perumal
output: html_document
---

```{r echo=FALSE}
now_asia <- function() {
   now <- Sys.time()
   attr(now, "tzone") <- "Asia/Calcutta"
   now
}
```
---
date: "Last compiled on `r now_asia()` , TZ: 'Asia/Calcutta'"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(pointblank)
```

### A Simple Example with the Basics
For our examples going forward, we’ll use the small_table dataset. It’s included in the pointblank package. It isn’t very large, which makes it great for simple examples. Here it is in its entirety:

```{r}
agent <- 
  create_agent(
    tbl = small_table,
    tbl_name = "small_table",
    label = "VALID-I Example No. 1"
  ) %>%
  col_is_posix(vars(date_time)) %>%
  col_vals_in_set(vars(f), set = c("low", "mid", "high")) %>%
  col_vals_lt(vars(a), value = 10) %>%
  col_vals_regex(vars(b), regex = "^[0-9]-[a-z]{3}-[0-9]{3}$") %>%
  col_vals_between(vars(d), left = 0, right = 5000) %>%
  interrogate()
```

The full-featured display-table-based report can be viewed by printing the agent object;

```{r}
report <- get_agent_report(agent)
report
```
