on:
  workflow_dispatch:
    
name: renv setup
  
jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    #container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")' 
          R -e 'renv::init()'
          R -e 'install.packages("dplyr", "rmarkdown")'
          R -e 'renv::snapshot()'
          R -e 'renv::restore()'
          
      - name: Identify and email articles
        #env: 
        #  repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
         Rscript -e 'rmarkdown::render(input = "demo.Rmd")'
            if [[ "$(git status --porcelain)" != "" ]]; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add *
            git commit -m "Auto update Report"
            git push origin
          fi