on:
  workflow_dispatch:
    
name: 11-gha_pointblank

jobs:
  render:
    name: Render my document
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}  
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install libcurl
        run: >
          sudo apt-get update && sudo apt-get install --yes libcurl4-openssl-dev
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::dplyr
            any::pointblank
      # - name: Install dplyr package
      #   run: Rscript -e 'install.packages("dplyr", repos = "https://cran.rstudio.com")'    
      # - name: Install pointblank package
      #   run: Rscript -e 'install.packages("pointblank", repos = "https://cran.rstudio.com")'   
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown", repos = "https://cran.rstudio.com")'
      - name: run-script
        run: Rscript -e 'rmarkdown::render("data-valid-demo.Rmd", output_file = "index.html")'   
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the pointblank results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"