on:
  workflow_dispatch:
  schedule:
    - cron:  "0 9 * * *"
    
name: 13-weather_pointblank scheduled report

jobs:
  render:
    name: Render report
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}  
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install libcurl
        run: >
          sudo apt-get update && sudo apt-get install --yes libcurl4-openssl-dev
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::dplyr
            any::pointblank
            any::openmeteo
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown", repos = "https://cran.rstudio.com")'
      - name: run-script
        run: Rscript -e 'rmarkdown::render("weather_rep.Rmd", output_file =  paste0("reports/weather_rep", format(as.POSIXlt(Sys.time(), tz = "Asia/Calcutta"),"_%Y%m%d_%H%M%S"), ".html"))'   
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the pointblank results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"